### ISSUE TITLE
storybook is not working

### ISSUE THREAD

**Issue by Harindulk** [mantinedev/mantine-next-template#22]
### @rtivital I'm getting this error when trying to start storybook
![image](https://user-images.githubusercontent.com/61319844/196039351-cab3690f-a291-4bc8-a5d5-38a0e2606ce4.png)

```

PS D:\GitHub\mantine-storybook> yarn storybook
yarn run v1.22.18
$ start-storybook -p 7001
info @storybook/react v6.5.9
info
info => Loading presets
info => Using implicit CSS loaders
(node:6184) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
r.js:214:10)
    at Array.<anonymous> (D:\GitHub\mantine-storybook\node_modules\loader-runner\lib\LoaderRunner.js:205:4)    at Storage.finished (D:\GitHub\mantine-storybook\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\GitHub\mantine-storybook\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9 
    at D:\GitHub\mantine-storybook\node_modules\graceful-fs\graceful-fs.js:123:16    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by rtivital** [comment]
Storybook does not support some node.js versions, use version 16.

**Comment by Harindulk** [comment]
ok thanks
